package utils_test

import (
    "bytes"
    "io"
    "io/ioutil"
    "os"
    "path/filepath"
    "strings"
    "testing"
    "time"

    "github.com/go-git/go-git/v5"
    "github.com/go-git/go-git/v5/config"
    "github.com/go-git/go-git/v5/plumbing/object"

    "github.com/simonwhitaker/gibo/utils"
)

// setupDummyRepo initializes a fake git repository at repoDir and creates two boilerplate files.
func setupDummyRepo(t *testing.T, repoDir string) {
    // Create the repository directory
    err := os.MkdirAll(repoDir, 0755)
    if err != nil {
    t.Fatalf("Failed to create repoDir: %v", err)
    }

    // Initialize a new git repository
    repo, err := git.PlainInit(repoDir, false)
    if err != nil {
    t.Fatalf("Failed to init repo: %v", err)
    }

    // Create two dummy .gitignore files: Python.gitignore and Node.gitignore.
    boilerplates := map[string]string{
    "Python.gitignore": "python boilerplate content",
    "Node.gitignore":   "node boilerplate content",
    }
    for filename, content := range boilerplates {
    path := filepath.Join(repoDir, filename)
    err := ioutil.WriteFile(path, []byte(content), 0644)
    if err != nil {
    t.Fatalf("Failed to write file %v: %v", filename, err)
    }
    }

    // Add the files and commit so that HEAD exists.
    wt, err := repo.Worktree()
    if err != nil {
    t.Fatalf("Failed to get worktree: %v", err)
    }

    // Add all files.
    err = wt.AddGlob("*.gitignore")
    if err != nil {
    t.Fatalf("Failed to add files: %v", err)
    }

    commitHash, err := wt.Commit("initial commit", &git.CommitOptions{
    Author: &object.Signature{
    Name:  "Tester",
    Email: "tester@example.com",
    When:  time.Now(),
    },
    })
    if err != nil {
    t.Fatalf("Failed to commit: %v", err)
    }

    // Print commit hash for debugging.
    t.Logf("Dummy commit: %v", commitHash.String())

    // For Update() test: set remote "origin" to point to the repo itself
    _, err = repo.CreateRemote(&config.RemoteConfig{
    Name: "origin",
    URLs: []string{"file://" + repoDir},
    })
    if err != nil && !strings.Contains(err.Error(), "already exists") {
    t.Fatalf("Failed to create remote: %v", err)
    }
}

// overrideCacheDir sets the environment variable to force utils.RepoDir to use a temporary directory.
func overrideCacheDir(t *testing.T, tempDir string) {
    // On Unix: os.UserCacheDir checks XDG_CACHE_HOME if set.
    err := os.Setenv("XDG_CACHE_HOME", tempDir)
    if err != nil {
    t.Fatalf("Failed to set XDG_CACHE_HOME: %v", err)
    }
}

// TestListBoilerplates verifies that ListBoilerplates returns the expected boilerplates.
func TestListBoilerplates(t *testing.T) {
    // Create a temporary directory to override the user cache directory.
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
    t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    boilerplates, err := utils.ListBoilerplates()
    if err != nil {
    t.Fatalf("ListBoilerplates failed: %v", err)
    }

    // Expect [Node, Python] sorted alphabetically.
    expected := []string{"Node", "Python"}
    if len(boilerplates) != len(expected) {
    t.Fatalf("Expected %d boilerplates, got %d", len(expected), len(boilerplates))
    }

    for i, name := range expected {
    if boilerplates[i] != name {
    t.Errorf("Expected boilerplate %v at index %d, got %v", name, i, boilerplates[i])
    }
    }
}

// TestPrintBoilerplate verifies that PrintBoilerplate prints the header and boilerplate content.
func TestPrintBoilerplate(t *testing.T) {
    // Create a temporary directory for the fake cache
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
    t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    // Capture Stdout
    oldStdout := os.Stdout
    r, w, err := os.Pipe()
    if err != nil {
    t.Fatalf("Failed to create pipe: %v", err)
    }
    os.Stdout = w

    // Call PrintBoilerplate with lowercase name (to test case-insensitive search)
    err = utils.PrintBoilerplate("python")
    if err != nil {
    t.Fatalf("PrintBoilerplate failed: %v", err)
    }

    w.Close()
    os.Stdout = oldStdout
    var buf bytes.Buffer
    _, err = io.Copy(&buf, r)
    if err != nil {
    t.Fatalf("Failed to read captured output: %v", err)
    }

    output := buf.String()
    if !strings.Contains(output, "python boilerplate content") {
    t.Errorf("Output missing expected boilerplate content: %v", output)
    }
    if !strings.Contains(output, "Generated by gibo") {
    t.Errorf("Output missing expected header: %v", output)
    }
}

// TestListBoilerplatesNoError verifies that ListBoilerplatesNoError returns the boilerplates without error.
func TestListBoilerplatesNoError(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
    t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    boilerplates := utils.ListBoilerplatesNoError()
    if len(boilerplates) == 0 {
    t.Errorf("Expected non-empty boilerplates list")
    }
}

// TestUpdate simulates updating the dummy repository and expects either "Already up to date" or "Updated".
func TestUpdate(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
    t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    // Call Update. Since we set remote pointing to itself, no changes are available.
    result, err := utils.Update()
    if err != nil {
    t.Fatalf("Update failed: %v", err)
    }

    // We expect either "Already up to date" (if pull returns an error of NoErrAlreadyUpToDate)
    // or "Updated" in case of a successful pull/reset.
    if result != "Already up to date" && result != "Updated" {
    t.Errorf("Unexpected update result: %v", result)
    }

    // To exercise the reset branch, one could simulate a pull error by tampering with the repository.
    // This test sticks to verifying the Update function completes.
}
// TestCloneIfNeededWhenRepoIsFile tests the behavior of cloneIfNeeded when the repo path exists as a file.
func TestCloneIfNeededWhenRepoIsFile(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
        t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    err = os.MkdirAll(filepath.Dir(repoDir), 0755)
    if err != nil {
        t.Fatalf("Failed to create parent directory for repoDir: %v", err)
    }
    // Create a file instead of a directory at repoDir.
    err = ioutil.WriteFile(repoDir, []byte("not a directory"), 0644)
    if err != nil {
        t.Fatalf("Failed to create file at repoDir: %v", err)
    }

    // Attempt to list boilerplates, which will trigger cloneIfNeeded.
    _, err = utils.ListBoilerplates()
    if err == nil {
        t.Errorf("Expected error when repoDir is not a directory, got nil")
    } else {
        if !strings.Contains(err.Error(), "is not a directory") {
            t.Errorf("Unexpected error: %v", err)
        }
    }
}

// TestPrintBoilerplateNotFound verifies that PrintBoilerplate returns an error when the specified boilerplate does not exist.
func TestPrintBoilerplateNotFound(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
        t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    // Call PrintBoilerplate with a non-existent boilerplate name.
    err = utils.PrintBoilerplate("nonexistent")
    if err == nil {
        t.Errorf("Expected error for non-existing boilerplate, got nil")
    } else {
        if !strings.Contains(err.Error(), "boilerplate not found") {
            t.Errorf("Unexpected error: %v", err)
        }
    }
}

// TestUpdateCorruptedRepo simulates a corrupted repository by removing the HEAD file, and expects Update to fail.
func TestUpdateCorruptedRepo(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache")
    if err != nil {
        t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    overrideCacheDir(t, tempDir)
    repoDir := utils.RepoDir()
    setupDummyRepo(t, repoDir)

    // Corrupt the repository by removing the HEAD file.
    headPath := filepath.Join(repoDir, ".git", "HEAD")
    err = os.Remove(headPath)
    if err != nil {
        t.Fatalf("Failed to remove HEAD file: %v", err)
    }

    // Call Update and expect an error due to the corrupted repository.
    _, err = utils.Update()
    if err == nil {
        t.Errorf("Expected error when updating a corrupted repo, got nil")
    }
}
// TestRepoDirOverride verifies that RepoDir returns the correct path when XDG_CACHE_HOME is set.
func TestRepoDirOverride(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache_override")
    if err != nil {
        t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    // Set XDG_CACHE_HOME to tempDir to override the default user cache directory.
    err = os.Setenv("XDG_CACHE_HOME", tempDir)
    if err != nil {
        t.Fatalf("Failed to set XDG_CACHE_HOME: %v", err)
    }

    expected := filepath.Join(tempDir, "gibo", "gitignore-boilerplates")
    dir := utils.RepoDir()
    if dir != expected {
        t.Errorf("RepoDir() returned %v, expected %v", dir, expected)
    }
}

// TestListBoilerplatesEmpty verifies that ListBoilerplates returns an empty list when
// the repo directory exists but contains no .gitignore files.
func TestListBoilerplatesEmpty(t *testing.T) {
    tempDir, err := ioutil.TempDir("", "gibo_test_cache_empty")
    if err != nil {
        t.Fatalf("Failed to create tempDir: %v", err)
    }
    defer os.RemoveAll(tempDir)

    // Set the XDG_CACHE_HOME environment variable so that RepoDir returns a location under tempDir.
    err = os.Setenv("XDG_CACHE_HOME", tempDir)
    if err != nil {
        t.Fatalf("Failed to set XDG_CACHE_HOME: %v", err)
    }

    repoDir := utils.RepoDir()
    // Create the repo directory but do not add any .gitignore files. This way ListBoilerplates will not find any.
    err = os.MkdirAll(repoDir, 0755)
    if err != nil {
        t.Fatalf("Failed to create repoDir: %v", err)
    }

    boilerplates, err := utils.ListBoilerplates()
    if err != nil {
        t.Fatalf("ListBoilerplates failed: %v", err)
    }

    if len(boilerplates) != 0 {
        t.Errorf("Expected empty boilerplates list, got %v", boilerplates)
    }
}